apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: blgs556rm-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/blgs556rm-dotnet-basic-gitops